# Generated by Django 3.1.4 on 2021-01-05 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('main', '0001_initial'), ('main', '0002_auto_20210102_0736'), ('main', '0003_auto_20210102_0812'), ('main', '0004_image'), ('main', '0005_image_description'), ('main', '0006_auto_20210105_0444')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок страницы')),
                ('coord_latitude', models.FloatField(blank=True, default=0, null=True, verbose_name='Координата на карте: широта')),
                ('coord_longitude', models.FloatField(blank=True, default=0, null=True, verbose_name='Координата на карте: долгота')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Тег description')),
                ('head', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Заголовок первого уровня')),
                ('keywords', models.TextField(blank=True, default='', null=True, verbose_name='Тег keywords')),
                ('text', models.TextField(blank=True, default='', null=True, verbose_name='Текст под слайдером')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главная страница',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Файл изображения')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.mainpage')),
                ('description', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Описание (содержимое атрибута alt)')),
            ],
            options={
                'verbose_name': 'Изображение на главной странице',
                'verbose_name_plural': 'Изображения на главной странице',
            },
        ),
    ]
