# Generated by Django 3.1.4 on 2021-01-05 07:56

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_squashed_0006_auto_20210105_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='', validators=[main.validators.validate_format, main.validators.validate_max_file_size], verbose_name='Файл изображения'),
        ),
    ]
