# Generated by Django 3.1.4 on 2021-01-02 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210102_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='coord_latitude',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Координата на карте: широта'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='coord_longitude',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Координата на карте: долгота'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Тег description'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='head',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Заголовок первого уровня'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='keywords',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Тег keywords'),
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='', null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='main.mainpage')),
            ],
            options={
                'verbose_name': 'Абзац текста на главной странице',
                'verbose_name_plural': 'Абзацы текста на главной странице',
            },
        ),
    ]
