# Generated by Django 3.1.4 on 2021-01-02 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210102_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Файл изображения')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.mainpage')),
            ],
            options={
                'verbose_name': 'Изображение на главной странице',
                'verbose_name_plural': 'Изображения на главной странице',
            },
        ),
    ]
