# Generated by Django 3.1.4 on 2021-01-03 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Описание (содержимое атрибута alt)'),
        ),
    ]
