# Generated by Django 3.1.4 on 2021-01-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='text',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Текст под слайдером'),
        ),
        migrations.DeleteModel(
            name='Paragraph',
        ),
    ]
