# Generated by Django 3.1.4 on 2021-01-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Название продукта')),
                ('photo', models.ImageField(upload_to='', verbose_name='Изображение продукта')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок страницы')),
                ('keywords', models.TextField(blank=True, default='', null=True, verbose_name='Тег keywords')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Тег description')),
                ('slug', models.SlugField(verbose_name='URL-адрес')),
            ],
        ),
    ]
